### PR TITLE
Fix bug to ensure data in `share*` columns of ICTR and PCTR indicator sums up to 1 for all three risk categories 

### LINKED ISSUE #173: In PCTR each `share*` column for each company must sum 1
> How comes that the company in this sample dataset has 0.25 for high risk but 0 for low and medium (see screenshot)?

> The three values in each column should always equate to 1 per company, as it measures the share of products in risk categories.

``` r
library(dplyr, warn.conflicts = FALSE)
library(tiltIndicator)
packageVersion("tiltIndicator")
#> [1] '0.0.0.9022'

company <- pctr_companies |> filter(company_id %in% first(company_id))
co2 <- pctr_ecoinvent_co2 |> slice(1)

co2 |>
  pctr_score_activities() |>
  pctr_score_companies(company)
#> # A tibble: 3 × 5
#>   company_id                           score share_all share_unit share_unit_sec
#>   <chr>                                <chr>     <dbl>      <dbl>          <dbl>
#> 1 powerstartmanufacturinggmbh_0000000… high       0.25       0.25           0.25
#> 2 powerstartmanufacturinggmbh_0000000… medi…      0          0              0   
#> 3 powerstartmanufacturinggmbh_0000000… low        0          0              0
```

<sup>Created on 2023-04-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### LINKED ISSUE #175: In ICTR each `share*` column for each company must sum to 1
``` r
library(dplyr, warn.conflicts = FALSE)
library(tiltIndicator)
packageVersion("tiltIndicator")
#> [1] '0.0.0.9022'

company <- ictr_companies |> filter(company_id %in% first(company_id))
inputs <- ictr_inputs |> slice(1)

inputs |>
  ictr_score_inputs() |>
  ictr_score_companies(company)
#> # A tibble: 3 × 6
#>   company_id              score share_all share_unit share_sector share_unit_sec
#>   <chr>                   <chr>     <dbl>      <dbl>        <dbl>          <dbl>
#> 1 fleischerei-stiefsohn_… high      0.143      0.143        0.143          0.143
#> 2 fleischerei-stiefsohn_… medi…     0          0            0              0    
#> 3 fleischerei-stiefsohn_… low       0          0            0              0
```

<sup>Created on 2023-04-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by kalashsinghal**
closes #173 
closes #175

@maurolepore this PR has the solution to resolve the bugs addressed in #173 and #175. Both the ICTR and PCTR indicators have the same bug, hence I have resolved both of them in the same PR. I have written the test for the ICTR indicator. I will also write a test for PCTR if you would like to see it. Thanks for your suggestions in advance!

### CODE REVIEW

**Review by maurolepore — APPROVED** [review]
LGTM.

Thanks @kalashsinghal! Indeed you fixed the problem I was thinking about. 

* I modified the test for ictr to make it self contained. This makes it easier to see all the context you need to understand a test.

* I  added a similar test for pctr

TODO:

Now that we have these functions fairly well covered by tests, it's time to remove the duplication. You can see how you had to do the same fix in two places.

**Comment by maurolepore** [comment]
@Tilmon 

@kalashsinghal fixed the bug. The current behaviour is this:

Even if the dataset `companies` has a `*uuid` value absent in the dataset `inputs` (or `co2`), all shares now still sum 1.

1. Is this sufficient?
2. Do we also need a warning showing the `*uuid` in companies that are missing from `inputs` (or `co2`)?
3. Do you instead want an error to stop the process and force the user to fix the data?

``` r
library(tiltIndicator)
packageVersion("tiltIndicator")
#> [1] '0.0.0.9027'

company <- tibble::tribble(
  ~company_id, ~activity_uuid_product_uuid,
          "a",                    "exists",
          "a",                    "absent",
)

inputs <- tibble::tribble(
  ~input_co2, ~input_sector,           ~unit, ~activity_uuid_product_uuid,
           9,   "transport", "metric ton*km",                    "exists",
)


ictr(company, inputs)
#> # A tibble: 3 × 6
#>   id    transition_risk score_all score_unit score_sector score_unit_sec
#>   <chr> <chr>               <dbl>      <dbl>        <dbl>          <dbl>
#> 1 a     high                    1          1            1              1
#> 2 a     medium                  0          0            0              0
#> 3 a     low                     0          0            0              0
```

<sup>Created on 2023-04-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

File: R/pctr_score_companies.R [hunk 1]
```diff
@@ -48,6 +48,7 @@ pctr_score_companies <- function(scored_activities, companies) {
   # scores in comparison to all products
   scores_all <- companies_scores |>
     group_by(.data$company_id, .data$score_all) |>
+    filter(!is.na(.data$score_all)) |>
```
Comment (maurolepore) [inline R/pctr_score_companies.R:51]: Bug fix

File: R/pctr_score_companies.R [hunk 2]
```diff
@@ -56,6 +57,7 @@ pctr_score_companies <- function(scored_activities, companies) {
   # scores in comparison to products with same unit
   scores_unit <- companies_scores |>
     group_by(.data$company_id, .data$score_unit) |>
+    filter(!is.na(.data$score_unit)) |>
```
Comment (maurolepore) [inline R/pctr_score_companies.R:60]: Bug fix.

File: R/pctr_score_companies.R [hunk 3]
```diff
@@ -64,6 +66,7 @@ pctr_score_companies <- function(scored_activities, companies) {
   # scores in comparison to products with same unit and sector
   scores_unit_sec <- companies_scores |>
     group_by(.data$company_id, .data$score_unit_sec) |>
+    filter(!is.na(.data$score_unit_sec)) |>
```
Comment (maurolepore) [inline R/pctr_score_companies.R:69]: Bug fix.

File: R/ictr_score_companies.R [hunk 4]
```diff
@@ -48,6 +48,7 @@ ictr_score_companies <- function(ecoinvent_scores, companies) {
   ## scores in comparison to all input products
   scores_all <- companies_scores |>
     group_by(.data$company_id, .data$score_all) |>
+    filter(!is.na(.data$score_all)) |>
```
Comment (maurolepore) [inline R/ictr_score_companies.R:51]: Bug fix.

File: R/ictr_score_companies.R [hunk 5]
```diff
@@ -56,6 +57,7 @@ ictr_score_companies <- function(ecoinvent_scores, companies) {
   ## scores in comparison to input products with same unit
   scores_unit <- companies_scores |>
     group_by(.data$company_id, .data$score_unit) |>
+    filter(!is.na(.data$score_unit)) |>
```
Comment (maurolepore) [inline R/ictr_score_companies.R:60]: Bug fix.

File: R/ictr_score_companies.R [hunk 6]
```diff
@@ -64,6 +66,7 @@ ictr_score_companies <- function(ecoinvent_scores, companies) {
   ## scores in comparison to input products with same input sector
   scores_sector <- companies_scores |>
     group_by(.data$company_id, .data$score_sector) |>
+    filter(!is.na(.data$score_sector)) |>
```
Comment (maurolepore) [inline R/ictr_score_companies.R:69]: Bug fix.

File: R/ictr_score_companies.R [hunk 7]
```diff
@@ -72,6 +75,7 @@ ictr_score_companies <- function(ecoinvent_scores, companies) {
   ## scores in comparison to input products with same unit and input sector
   scores_unit_sec <- companies_scores |>
     group_by(.data$company_id, .data$score_unit_sec) |>
+    filter(!is.na(.data$score_unit_sec)) |>
```
Comment (maurolepore) [inline R/ictr_score_companies.R:78]: Bug fix
